### PR TITLE
journal-week-3

### PR DESCRIPTION
**Pull request by JessyRiordan**

### CODE REVIEW

**Comment by Epicurean306** [comment]
Great draft. Nice idea focusing on online presence and networking, and I like the tutorial focus on critical GitHub workflow commands! :+1:

**Comment by MStaehling** [comment]
Loved the tutorial and nice talking about how important social media is :+1:

**Comment by pcreglow** [comment]
Love the images! That tutorial has gone to another level. Next week, follow-up tutorial on how to add images in markdown? I noticed the same errors in the reflective journal that @sjoyal pointed out. :+1:

**Comment by Epicurean306** [comment]
Really nice visuals in the merge conflict tutorial. :+1:  As a Twitter newbie myself, I appreciated your reflective post as well.

**Pull request merged**
