### PR TITLE
remodeling

### PR DESCRIPTION
**Pull request by JessyRiordan**
* **HALFTIME Journal**
  * [x] Time for some `remodeling`...
  * [x] Moving day, `_posts`...!
  * [x] You got that `yo h5bp`?
  * [x] Bower and NPM, back in the saddle.
  * [x] Browser? Sync'd.
  * [x] Skitched that layout?
  * [x] Breakpoints?
  * [x] Made a plan...
  * [x] Wrote it down...
  * [x] Broke it up...
  * [x] First feature:
    * [x] Committed and pushed!
    * [x] PR open!
    * [x] PR merged!
  * [x] Second feature:
    * [x] Committed and pushed!
    * [x] PR open!
    * [x] PR merged!
  * [ ] **BEAST MODE** Journal entry draft...

### CODE REVIEW

**Comment by JessyRiordan** [comment]
* **HALFTIME Journal**
  * [ ] Time for some `remodeling`...
  * [ ] Moving day, `_posts`...!
  * [ ] You got that `yo h5bp`?
  * [ ] Bower and NPM, back in the saddle.
  * [ ] Browser? Sync'd.
  * [ ] Skitched that layout?
  * [ ] Breakpoints?
  * [ ] Made a plan...
  * [ ] Wrote it down...
  * [ ] Broke it up...

**Comment by JessyRiordan** [comment]
https://github.com/JessyRiordan/jessyriordan.github.io/issues/9

**Comment by JessyRiordan** [comment]
[Reference Implementation for Blog](http://uzii.udemo.co/?product=octal_jekyll)

**Comment by al-the-x** [comment]
In checking your specs, don't forget the footer... It's often overlooked, but it contains valuable information on how to contact the author of the site. Which is you. Also note how the navigation header locks to the top of the viewport as you scroll past the decorative header. And there's a button in the footer that controls pagination.

**Pull request merged**
